### ISSUE TITLE
Implement Server-Side Audio Transcoder

### ISSUE THREAD

**Issue by pyldin601** [pyldin601/myownradio#269]
### Objective

Create a server-side service for transcoding audio files into browser-compatible formats.

### Requirements

1. Implement a new POST route `/audio/transcode` that accepts a JSON payload in the following format:

    ```json
    {
      "source_url": "http://example.com/audio/file.wav"
    }
    ```

2. The service should fetch the audio file from the `source_url`.

3. Transcode the audio to a browser-compatible format if it is not already in one. The whitelisted formats that don't require transcoding are MP3 and AAC.

4. Stream the audio file back to the client, ensuring that transcoded files are not stored on the disk to save storage space.

### TODOs

- [ ] Implement a POST route at `/audio/transcode` that accepts a JSON payload.
- [ ] Integrate logic to fetch the audio file from the `source_url`.
- [ ] Determine the audio file format. If it is MP3 or AAC, pipe it directly to the client.
- [ ] If the audio format is not whitelisted, use `static-ffmpeg` to transcode it to AAC.
- [ ] Stream the (transcoded) audio file back to the client.
- [ ] Ensure that no files are stored on the disk during this process.
- [ ] Test the service with various audio formats to ensure that it works as expected.
