### ISSUE TITLE
Database Models Cleanup

### ISSUE THREAD

**Issue by pyldin601** [pyldin601/myownradio#281]
#### Brief Task Description:
Perform a cleanup operation on the existing database models to optimize structure and naming conventions.

#### To-Do List:
- [ ] Check which fields are not used and remove them
- [ ] Check if some data can be moved out of the database to static assets like JSON files and proceed to move them
- [ ] Standardize `id` field naming; replace `tid`, `sid`, etc., with traditional `id` naming
