### ISSUE TITLE
story: support tracker music

### ISSUE THREAD

**Issue by pyldin601** [pyldin601/myownradio#45]
As a user I want to create a radio station and stream music in tracker formats (xm, s3m, mod, etc...).

Tasks:
- [x] Enable `libmodplug` decoder in `ffmpeg`
- [x] Tweak backend images for using this `ffmpeg`
- [x] Enable support of tracker music in upload endpoint
- [x] Enable support of tracker music in upload UI
